### ISSUE TITLE
GPXTrackPoint extensions property is nil

### ISSUE THREAD

**Issue by mishamoe** [vincentneo/CoreGPX#36] opened 2019-05-12 17:08 UTC
I'm trying to parse GPX file exported from Strava app. 
It contains track points in the following format.
```xml
<trkpt lat="50.3782100" lon="30.4798930">
    <ele>191.6</ele>
    <time>2019-05-09T09:56:01Z</time>
    <extensions>
        <gpxtpx:TrackPointExtension>
            <gpxtpx:hr>138</gpxtpx:hr>
        </gpxtpx:TrackPointExtension>
    </extensions>
</trkpt>
```

After parsing property `extensions` of `GPXTrackPoint` is nil.
Is it possible to extract `hr` value?

**Comment by vincentneo** [comment] 2019-05-12 17:47
First off, thanks for using CoreGPX!

For now, parsing of extensions related stuff requires one to modify GPXParser, to allow parsing of extensions. I could have made it parse without such factors, but as I didn’t have the time, and that there seemed no demand for it yet, I didn’t really do anything about it.

The idea would be to allow it as like a regular XML parser would. Something like that. Now that you have requested for this, it might be time for me to work on it! Once I have the free time here and there I will try to sort things out.

GPXParser is also in such a mess too. That’s something that I would want to clear up as well, when I got the time.

If you need this urgently, I might be able to edit the code for you within a few days time. (As a temporary fix, case by case kind of fix)

**Comment by mishamoe** [comment] 2019-05-13 11:17
It would be nice if you could provide the fix in the nearest future. 

I've created a fork to solve this issue in a quick way. So I'll use it in my project. 
But I'll come back to original CoreGPX when the fix will be available.

Thanks!

**Comment by vincentneo** [comment] 2019-05-13 14:01
@mishamoe alright!

**Comment by vincentneo** [comment] 2019-05-18 11:28
Hi @mishamoe, 
do check out branch [features/GPXExtensions](https://github.com/vincentneo/CoreGPX/tree/features/GPXExtensions) to see if it fits what's needed. If there's things that you feel should be added/removed, do tell me!

Once confirmed to be good and working, I will extend the functionality to other classes as well. 

As for the additional clutter, I intend to fix it only in the future, which meant that the parser is still barely readable.

Thanks for using CoreGPX!

**Comment by mishamoe** [comment] 2019-05-19 13:41
Hi @vincentneo,

I've checked on the example of track point provided earlier and it seems like `extensions` property is still nil. Could you use this particular example for testing?

I have one more question. Considering provided example and your changes, how exactly can I extract `gpxtpx:hr` value from the instance of `GPXExtensions`?

Thanks!

**Comment by vincentneo** [comment] 2019-05-19 13:49
Hi @mishamoe, 
my apologies that I forgot to tell you how to get the values. To get the values in `GPXExtensions`, you can get them in the variable `attributes` in it. (I have also noticed that I did not set them as public earlier on, latest commit should have)

In this case, `extensions` property should not be nil after using the branch. It is advised to use the latest commit from branch `features/GPXExtensions`, committed minutes ago, and also, do remember to clean the project (Shift + Cmd + K)

Will attempt to check with your example as well later.

Thank you!

**Comment by vincentneo** [comment] 2019-06-21 14:06
Hi @mishamoe,

I have pushed a new commit that aims to make extensions stuff easier. 

Let's use back this code as example:
```XML
<trkpt lat="50.3782100" lon="30.4798930">
    <ele>191.6</ele>
    <time>2019-05-09T09:56:01Z</time>
    <extensions>
        <gpxtpx:TrackPointExtension>
            <gpxtpx:hr>138</gpxtpx:hr>
        </gpxtpx:TrackPointExtension>
    </extensions>
</trkpt>
```
`let trackpoint = GPXTrackPoint()`, 
to access extensions, use `trackpoint.extensions["gpxtpx:TrackPointExtension"]`, and you will get a dictionary, in this case, will be `["gpxtpx:hr", "138"]`

if there is no parent tag (i.e. `<gpxtpx:TrackPointExtension>`), simply use `trackpoint.extensions[nil]` to get a dictionary with the intended data.

Hope this syntax works for you! As I've said in the previous reply, you can find it in #37 pull request. Feedback will be appreciated.

This is just a preliminary extensions parsing format, and I will overhaul it once I deal with issue #39 .

Thank you!

**Closed** 2019-06-30 06:16 UTC
Labels: enhancement, parsing
